### ISSUE TITLE
gta5_source_pretrained

### ISSUE THREAD

**Issue by EDENpraseHAZARD** [lukemelas/pixmatch#1]
Hi author, thanks for your great job! I notice that for GTA5-to-Cityscapes, you used  a model pretrained on the source GTA5. I want to know the training details of gta5-source-pretrained model and I want to train this pretrain from scratch.

**Comment by lukemelas** [comment]
Hello,

I used the pretrained model from here: https://github.com/ZJULearning/MaxSquareLoss. There are details about training in that repo. 

Hope this helps!
Luke 

P.S. Nice GitHub name

**Comment by EDENpraseHAZARD** [comment]
Thank you!

P.S. I use my favourite football player's name as my GitHub name.
