### ISSUE TITLE
About target size

### ISSUE THREAD

**Issue by EDENpraseHAZARD** [lukemelas/pixmatch#2]
Dear author, thanks for your great job. I found that you use [1280,640] as target img size, and common UDA semantic segmentation methods use [1024, 512]. Then I tried to use [1024, 512] as trg img size but got worse result. I wonder whether the trg img size is an important hyperparameter. Why you choose [1280, 640] ?

**Comment by lukemelas** [comment]
Hi, thanks for the comment. Yes, it's unfortunate that most new methods are now using 640. For example, [MaxSquareLoss](https://github.com/ZJULearning/MaxSquareLoss)  also uses 640. That being said, it should only make a small difference. 

Hope this helps,
Luke
