### ISSUE TITLE
Problem: use  the max-square loss

### ISSUE THREAD

**Issue by leo-hao** [lukemelas/pixmatch#3]
Hi,
Thanks for sharing this great work.
I wonder to known how to use the max-square loss.
Looking forward to your reply！

**Comment by leo-hao** [comment]
Dear author,
I am a beginner , my question may be silly, but I am very much looking forward to your answer. 
Best of luck!

**Comment by lukemelas** [comment]
Hi, thanks for the question. Perhaps you're looking for the [MaxSquareLoss repo](https://github.com/ZJULearning/MaxSquareLoss)?

**Comment by leo-hao** [comment]
Hi，
Thanks for your reply, I solved the problem through your tips.
Before aug loss, I added max-square loss as target loss , like MaxSquareLoss do in their work 'solve_gta5.py'.
Did I do it right?
Or, should I add it to the aug loss?
Best wishes~

**Comment by leo-hao** [comment]
I got the answer from you paper. There should be no target loss here. The paper has already said that no gradient is needed here. So I need change the CrossEntropyLoss to MaxSquareloss in Aug Loss. 
Thanks for sharing this great work. Wish you good health and every success！
